### ISSUE TITLE
How to add more scala modules

### ISSUE THREAD

**Issue by jstaursky** [edmcman/ghidra-scala-loader#4]
How would I go about adding say `scala.util.parsing.json` module to this?

**Comment by edmcman** [comment]
It should be a matter of dropping the right `.jar` file into the `lib` directory, I think.  I would guess it is [this one](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-parser-combinators_2.12/1.1.2).

**Comment by jstaursky** [comment]
Yes! That was it. Sorry for the basic question I am new to the java ecosystem. FYI I built on ghidra 9.3 recently and got warnings of some depreciated functions being used. Everything still works but figured I would give you a heads up.

**Comment by edmcman** [comment]
Glad it worked!  And thanks for the heads up.
